### ISSUE TITLE
Tracker for first PyPI release

### ISSUE THREAD

**Issue by santacodes** [pybamm-team/pybamm-cookie#26]
# Overview
This issue tracks all the tasks that need to be checked before the first PyPI release for the `pybamm-cookie` template.

### Migrations
- [x] Migrate the following contents of the project to the template - 
   - `entry points`, for both `parameter_sets` and `models`. #27 
   - `tests` specifically to be shipped to the user inside the template, i.e. the `entry points` tests and an example test file for the users to add test cases. #29 
   - `models` & `parameter_sets` included in the project, i.e. `SPM` and `Chen2020`. #27 
   - `nox-sessions` that are not present in the template. They would be - `unit tests`(yet to be separated), `coverage` and `dev` session. #29 
   - Move suitable `test_on_push` CI to the template. #29 
 ### Features
- [x] Separate `nox sessions` for **tests for project** and **tests for template**. #29 
- [x] Two steps in the `CI` for **tests for project** and **tests for template**. #29 
- [ ] Add `example notebooks` for using `pybamm-cookie` template and entry points.
- [x] Add the `reservoir model`. #30
- [x] Script for automatic `git init` while project generation using the template. Could be referred [here](https://github.com/osl-incubator/scicookie/blob/428785d48d95fa04d17463dd144b5508ab9c77f5/src/scicookie/hooks/post_gen_project.py#L335-L398). #32 ---> #34
- [x] Add `Dependabot` for CI. #28 
- [x] Migration to `copier`. #34
- [x] CD for publishing. #48 
- [x] Add a wrapper CLI for generating a project using `copier`. #36 
- [x] Add `setuptools` backend. #37 
- [ ] Add a basic CI for `gitlab-ci.yml`.
- [x] Add versioning support for git archives #42

### Misc
- [x] Attribute inspirations #43  #45
- [x] Rename to `pybamm-cookie` #46 
- [x] More documentation in README (maybe the logo too?) #47 

#### PS
If there is something else to add or is missing, please feel free to edit this comment and append it.

**Comment by santacodes** [comment]
@Saransh-cpp @agriyakhetarpal @arjxn-py I looked into `copier` and supporting it would take a fair bit of change in the template.

- Modifying the jinja structure with respect to what `copier` supports, i.e. we would have to change all the variables mostly with the `{{cookiecutter.key}}`. This should be easy though, we don't have to change much, just rename things from `{{ cookiecutter.something }}` -> `{{ something }}`.
- Changing the `test_template_generation` completely, unfortunately, we would have to rewrite this completely because `cookiecutter` and `copier` work differently.
- Hooks have to be changed though I feel `copier` has better support for that, we don't have to write some kind of a script and add it to a `hooks/` directory, rather we could just add it in the `coper.yml` file under the `tasks` key.

I think that is mostly the gist of the copier migration/support, I would prefer we completely move to `copier` rather than just supporting them both as we are also giving the users a `cli` interface, and `copier` already provides a library/API for generating the project. I saw some `pytest-copier` libraries for testing, but I felt like they weren't maintained, but that was also the case with `pytest-cookies` so I think it might be reliable because we will just be using them for 2 test cases.

**Comment by agriyakhetarpal** [comment]
Thanks for sharing your thoughts, @santacodes. I agree that while migrating to `copier` is a lot of work, it's useful work, and we would be better off supporting just one tool, as is the case for the CLI. We would be glad to review these changes if you could put together a PR!

Regarding the hooks, I think many of them are supported through extensions for `copier`, which we can selectively enable/install based on our project's requirements. `copier` also supports updating a generated project from an updated template, but that can be picked up in a follow-up PR.

**Comment by Saransh-cpp** [comment]
Looking at this issue, `gitlab-ci.yml` is not a priority. We should go ahead with the release without adding support for gitlab.

**Comment by santacodes** [comment]
@Saransh-cpp @agriyakhetarpal @arjxn-py Do we need example notebooks for this project? I think it was discussed previously in one of the meetings and I added it to this tracker list.

**Comment by agriyakhetarpal** [comment]
I feel an example notebook would be nice to showcase since it would give people an idea of how to add docs and integrate MyST-NB with their project. However, I don't think it is a blocker for the first release, and it can be picked up anytime.

**Comment by agriyakhetarpal** [comment]
Looking at the tracker, all we have left is a logo (nice-to-have) and a publishing workflow (needed). You can set up an environment in the repository, and create a project named `pybamm-cookie` on PyPI for now using a personal account, wherein we can configure trusted publishing (feel free to add us as authors there if you would like a additional pairs of eyes). We can then move it to a PyBaMM-specific organisation whenever it gets set up.

**Comment by santacodes** [comment]
> Looking at the tracker, all we have left is a logo (nice-to-have) and a publishing workflow (needed). You can set up an environment in the repository, and create a project named `pybamm-cookie` on PyPI for now using a personal account, wherein we can configure trusted publishing (feel free to add us as authors there if you would like a additional pairs of eyes). We can then move it to a PyBaMM-specific organisation whenever it gets set up.

Sure that sounds good!

**Comment by brosaplanella** [comment]
Sorry I have been disconnected these past to weeks. All the progress looks amazing, well done!

**Comment by agriyakhetarpal** [comment]
Now that the first (and second) releases are up on PyPI, we should be in a safe position to close this. Thanks, @santacodes!
